import { useEffect, useState } from 'react';
import { PageHeader, Panel, Button, Field, Input, Select, Textarea, Toggle, Tabs, Notice, UniversityLock } from '../../components/ui';
import { ActionError, useAction } from '../../components/feedback';
import { AppearancePicker } from '../student/Settings';
import { adminService } from '../../services/admin-service';
import { useResource } from '../../hooks/useResource';

const CONFIG = {
  general: { title: 'Platform identity', description: 'Public information for the independent CGPA+ UniPort platform.', fields: [{ key: 'productName', label: 'Product name', type: 'text' }, { key: 'supportEmail', label: 'Public support email', type: 'email' }, { key: 'description', label: 'Product description', type: 'textarea' }] },
  academic: { title: 'Academic configuration', description: 'The backend controls which published academic version is active.', fields: [{ key: 'publishedVersionId', label: 'Published academic version ID', type: 'text' }, { key: 'policyReference', label: 'Grading policy reference', type: 'text' }, { key: 'allowStudentResultEntry', label: 'Student result entry', description: 'Allow authenticated students to submit results.', type: 'toggle' }, { key: 'requireServerValidation', label: 'Require server validation', description: 'Backend policy must validate every stored calculation.', type: 'toggle' }] },
  notifications: { title: 'Notification delivery', description: 'Configure the non-secret defaults used by the notification backend.', fields: [{ key: 'senderName', label: 'Display sender name', type: 'text' }, { key: 'allowScheduledDelivery', label: 'Scheduled delivery', description: 'Enable scheduled jobs when the backend supports them.', type: 'toggle' }, { key: 'emailEnabled', label: 'Email channel', description: 'The server supplies provider configuration and secrets.', type: 'toggle' }] },
  payments: { title: 'Payment configuration', description: 'No payment secrets belong in this interface.', fields: [{ key: 'publicProviderName', label: 'Public provider name', type: 'text' }, { key: 'currency', label: 'Display currency', type: 'select', options: [{ value: 'NGN', label: 'Nigerian naira (NGN)' }] }, { key: 'paymentsEnabled', label: 'Payment availability', description: 'The backend must verify provider readiness before accepting payment.', type: 'toggle' }] },
  reports: { title: 'Report presentation', description: 'Reports must never be represented as official university transcripts.', fields: [{ key: 'reportFooter', label: 'Additional report footer', type: 'textarea' }, { key: 'studentReportsEnabled', label: 'Student report requests', description: 'Allow academic report requests when authorized.', type: 'toggle' }] },
  support: { title: 'Support configuration', description: 'Public-facing support settings and backend workflow preferences.', fields: [{ key: 'supportEmail', label: 'Public inbox email', type: 'email' }, { key: 'responseExpectation', label: 'Published response expectation', type: 'text' }, { key: 'requestsEnabled', label: 'Accept support requests', description: 'Backend rules still enforce authenticated access and rate limits.', type: 'toggle' }] },
  security: { title: 'Security policies', description: 'These are configuration requests, not frontend enforcement. All decisions belong to the backend.', fields: [{ key: 'requireVerifiedEmail', label: 'Require verified email', description: 'Backend policy for protected account actions.', type: 'toggle' }, { key: 'requireAdminMfa', label: 'Require administrator MFA', description: 'Must be enforced by authentication and server authorization.', type: 'toggle' }, { key: 'sessionTimeoutMinutes', label: 'Requested session timeout (minutes)', type: 'number' }] },
};
export default function AdminSettings() {
  const [tab, setTab] = useState('general');
  const resource = useResource(() => adminService.getSettings({ section: tab }), [tab], tab !== 'appearance');
  const [form, setForm] = useState({});
  const action = useAction();
  useEffect(() => { setForm(resource.data || {}); action.clear(); }, [tab, resource.data]);
  const config = CONFIG[tab];
  return <><PageHeader eyebrow="PLATFORM PREFERENCES" title="Admin settings." description="Backend-controlled configuration, with clear separation from local appearance preferences." /><Tabs value={tab} onChange={setTab} options={['general', { value: 'academic', label: 'Academic configuration' }, 'notifications', 'payments', 'reports', 'support', 'security', 'appearance']} />{tab === 'appearance' ? <Panel title="Your admin workspace" description="This appearance preference applies only to your browser, not all users."><AppearancePicker /></Panel> : <Panel title={config.title} description={config.description}>{tab === 'general' && <UniversityLock />}{resource.error && <Notice>Saved settings are unavailable. This is an unsaved configuration draft; no backend policy has been changed.</Notice>}{tab === 'reports' && <Notice><strong>Required report identity:</strong> CGPA+ Academic Report. Not an official University of Port Harcourt transcript.</Notice>}<form className="form-stack admin-settings-form" onSubmit={e => { e.preventDefault(); action.run(() => adminService.updateSettings({ section: tab, settings: form }), resource.refresh, 'The backend accepted the settings update.'); }}>{config.fields.map(f => f.type === 'toggle' ? <Toggle key={f.key} label={f.label} description={f.description} checked={!!form[f.key]} onChange={v => setForm({ ...form, [f.key]: v })} /> : <Field key={f.key} label={f.label}>{f.type === 'textarea' ? <Textarea value={form[f.key] || ''} onChange={e => setForm({ ...form, [f.key]: e.target.value })} /> : f.type === 'select' ? <Select value={form[f.key] || ''} onChange={e => setForm({ ...form, [f.key]: e.target.value })}><option value="">Select a value</option>{f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</Select> : <Input type={f.type} min={f.type === 'number' ? 1 : undefined} value={form[f.key] ?? ''} onChange={e => setForm({ ...form, [f.key]: e.target.value })} placeholder="Not configured" />}</Field>)}<ActionError error={action.error} /><div className="form-actions"><Button variant="outline" onClick={() => setForm(resource.data || {})}>Discard draft</Button><Button type="submit" busy={action.busy}>Save configuration</Button></div></form></Panel>}<Notice icon="shield">Firebase Admin SDK, custom claims, Firestore rules and all server secrets belong to the backend. This settings page is not an authorization system.</Notice></>;
}