import { useEffect, useState } from 'react';
import { PageHeader, Button, Badge, Tabs, AsyncSelect, Stat } from '../../components/ui';
import { ConnectionState, Modal } from '../../components/feedback';
import { DataTable, SearchBox, StatusFilter } from '../../components/table';
import { LineChart } from '../../components/charts';
import { adminService } from '../../services/admin-service';
import { useResource } from '../../hooks/useResource';
import { number, titleCase, date } from '../../utils/formatting';
import { resultColumns } from '../student/Academic';

function StudentDetail({ studentId, initialTab = 'profile', onClose }) {
  const [tab, setTab] = useState(initialTab);
  const resource = useResource(() => adminService.getStudent(studentId), [studentId], !!studentId);
  const academic = useResource(() => adminService.getAcademicProfile(studentId), [studentId], !!studentId);
  useEffect(() => { setTab(initialTab); }, [studentId, initialTab]);
  return <Modal open={!!studentId} onClose={onClose} title={resource.data?.fullName || 'Student details'} description="Personal and academic data require authorized backend access." wide><Tabs value={tab} onChange={setTab} options={['profile', 'academic', 'results', 'GPA history', 'support history']} />{tab === 'academic' ? <ConnectionState resource={academic} title="academic profile" emptyTitle="No academic profile found.">{p => <dl className="detail-grid">{[['universityName', 'University'], ['facultyName', 'Faculty'], ['departmentName', 'Department'], ['programmeName', 'Programme'], ['currentLevelName', 'Level'], ['admissionSessionName', 'Admission session'], ['currentSessionName', 'Current session'], ['currentSemesterName', 'Semester']].map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{p[key] || '--'}</dd></div>)}</dl>}</ConnectionState> : <ConnectionState resource={resource} title="student details" emptyTitle="Student not found.">{data => <>{tab === 'profile' && <><dl className="detail-grid">{[['fullName', 'Full name'], ['email', 'Email'], ['phone', 'Phone'], ['accountStatus', 'Account status'], ['createdAt', 'Registered']].map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{key === 'createdAt' ? date(data[key]) : data[key] || '--'}</dd></div>)}</dl><div className="stats-grid stats-three"><Stat label="Current CGPA" value={number(data.summary?.cgpa)} accent /><Stat label="Current GPA" value={number(data.summary?.gpa)} /><Stat label="Credits" value={number(data.summary?.totalCredits, 0)} /></div></>}{tab === 'results' && <DataTable columns={resultColumns} resource={{ status: 'success', data: data.results || [], error: null, refresh: resource.refresh }} emptyTitle="No academic results available." />}{tab === 'GPA history' && <LineChart values={(data.gpaHistory || []).map(r => r.gpa)} labels={(data.gpaHistory || []).map(r => r.label)} max={data.summary?.maxPoint || 5} />}{tab === 'support history' && <DataTable resource={{ status: 'success', data: data.tickets || [], error: null, refresh: resource.refresh }} columns={[{ key: 'id', label: 'Request' }, { key: 'subject', label: 'Subject' }, { key: 'status', label: 'Status', render: titleCase }, { key: 'createdAt', label: 'Date', render: date }]} emptyTitle="No support history available." />}</>}</ConnectionState>}</Modal>;
}

export default function Students() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [faculty, setFaculty] = useState('');
  const [student, setStudent] = useState(null);
  const [tab, setTab] = useState('profile');
  const resource = useResource(() => adminService.getStudents({ status, facultyId: faculty }), [status, faculty]);
  const columns = [{ key: 'fullName', label: 'Name', render: v => <strong>{v}</strong> }, { key: 'email', label: 'Email' }, { key: 'facultyName', label: 'Faculty' }, { key: 'departmentName', label: 'Department' }, { key: 'programmeName', label: 'Programme' }, { key: 'levelName', label: 'Level' }, { key: 'cgpa', label: 'CGPA', render: v => number(v) }, { key: 'accountStatus', label: 'Status', render: v => <Badge tone={v === 'active' ? 'success' : v === 'suspended' ? 'danger' : 'neutral'}>{titleCase(v) || '--'}</Badge> }, { key: 'academic', label: 'Academic profile', render: (_, row) => <Button variant="ghost" className="button-small" onClick={() => { setTab('academic'); setStudent(row.id); }}>View academic</Button> }];
  return <><PageHeader eyebrow="STUDENTS AT THE CENTER" title="The student directory." description="Find an account, review academic context and understand a student's journey." actions={<Button variant="outline" icon="refresh" onClick={resource.refresh}>Refresh</Button>} /><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search name, email or programme..." /><StatusFilter value={status} onChange={setStatus} options={['active', 'pending', 'suspended']} /></div><div className="admin-student-filters"><AsyncSelect label="Faculty" loader={() => adminService.getFaculties()} required={false} value={faculty} onChange={e => setFaculty(e.target.value)} placeholder="All faculties" /></div><DataTable columns={columns} resource={resource} search={search} onView={row => { setTab('profile'); setStudent(row.id); }} emptyTitle="No students loaded." emptyDescription="Student accounts and their academic information come from the authorized admin service." /><StudentDetail studentId={student} initialTab={tab} onClose={() => setStudent(null)} /></>;
}