import { useEffect, useState } from 'react';
import { PageHeader, Button, Panel, Field, Input, Select, AsyncSelect, Notice, Badge } from '../../components/ui';
import { Modal, ConfirmModal, ActionError, useAction, ConnectionState } from '../../components/feedback';
import { DataTable, SearchBox } from '../../components/table';
import { useResource } from '../../hooks/useResource';
import { academicService } from '../../services/academic-service';
import { authService } from '../../services/auth-service';
import { number, titleCase } from '../../utils/formatting';
import { GRADE_OPTIONS, FALLBACK_LEVELS, FALLBACK_SEMESTERS, FALLBACK_SESSIONS, academicPeriodLabel } from '../../data/uniport-catalogue';

const blank = { code: '', title: '', credits: '', grade: '', points: '', sessionId: '', semesterId: '', levelId: '' };
const blankCourse = { code: '', title: '', credits: '', sessionId: '', semesterId: '', levelId: '' };

async function loadOrFallback(loader, fallback) { try { const rows = await loader(); return Array.isArray(rows) && rows.length ? rows : fallback; } catch { return fallback; } }
const labelFor = (rows, id) => rows.find(row => row.id === id)?.name || id || '--';
const yearLabelFor = levelId => FALLBACK_LEVELS.find(row => row.id === levelId)?.yearName || labelFor(FALLBACK_LEVELS, levelId);
const periodLabelFor = (levelId, semesterId) => academicPeriodLabel(levelId, semesterId);

export const resultColumns = [
  { key: 'sessionName', label: 'Session' }, { key: 'semesterName', label: 'Semester' }, { key: 'levelName', label: 'Level' },
  { key: 'code', label: 'Course code', render: v => <strong>{v}</strong> }, { key: 'title', label: 'Course title' },
  { key: 'credits', label: 'Credit units' }, { key: 'grade', label: 'Grade', render: v => <Badge>{v || '--'}</Badge> },
  { key: 'points', label: 'Grade points' }, { key: 'qualityPoints', label: 'Quality points' },
  { key: 'status', label: 'Status', render: v => <Badge tone={v === 'failed' ? 'danger' : v === 'passed' ? 'success' : 'neutral'}>{titleCase(v) || 'Recorded'}</Badge> },
];

export function ResultEditor({ open, onClose, record, onSaved, initialCourse }) {
  const [form, setForm] = useState(blank); const action = useAction();
  useEffect(() => { if (!open) return; let active = true; action.clear(); (async () => { let defaults = {}; try { const profile = await academicService.getProfile(); defaults = { sessionId: profile?.currentSessionId || '', semesterId: profile?.currentSemesterId || '', levelId: profile?.currentLevelId || '' }; } catch {} if (!active) return; setForm(record ? Object.fromEntries(Object.keys(blank).map(key => [key, record[key] ?? blank[key]])) : { ...blank, ...defaults, ...(initialCourse || {}), sessionId: initialCourse?.sessionId || defaults.sessionId || FALLBACK_SESSIONS.find(x => x.name === '2026/2027')?.id || FALLBACK_SESSIONS[FALLBACK_SESSIONS.length - 1].id, semesterId: initialCourse?.semesterId || defaults.semesterId || FALLBACK_SEMESTERS[0].id, levelId: initialCourse?.levelId || defaults.levelId || 'level-300' }); })(); return () => { active = false; }; }, [open, record, initialCourse]);
  const change = key => e => setForm(prev => ({ ...prev, [key]: e.target.value }));
  const gradeChange = e => { const grade = e.target.value; const option = GRADE_OPTIONS.find(item => item.grade === grade); setForm(prev => ({ ...prev, grade, points: option ? option.points : '' })); };
  const contextualized = form.sessionId && form.semesterId && form.levelId;
  const sessionLoader = () => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS);
  const semesterLoader = () => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS);
  const levelLoader = () => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS);
  return <Modal open={open} onClose={onClose} title={record ? 'Edit academic result' : 'Add an academic result'} description="Choose the Year and semester first. Your results will be grouped as Year 1, Year 2, Year 3 and so on, with First Semester and Second Semester inside each year." wide>
    <form className="form-stack" onSubmit={e => { e.preventDefault(); if (!contextualized || !form.grade) return; const payload = { ...form, code: form.code.trim().toUpperCase(), credits: Number(form.credits), points: Number(form.points) }; action.run(() => record ? academicService.updateResult(record.id, payload) : academicService.saveResult(payload), () => { onSaved?.(); onClose(); }, record ? 'Your result was updated.' : 'Your result was saved.'); }}>
      <div className="form-grid">
        <Field label="Course code"><Input value={form.code} onChange={change('code')} placeholder="e.g. CSC 301" required maxLength={30} /></Field>
        <Field label="Course title"><Input value={form.title} onChange={change('title')} placeholder="Full course title" required maxLength={180} /></Field>
        <Field label="Credit units"><Input value={form.credits} onChange={change('credits')} type="number" required min="1" step="1" inputMode="numeric" /></Field>
        <Field label="Grade"><Select value={form.grade} onChange={gradeChange} required><option value="">Select your grade</option>{GRADE_OPTIONS.map(item => <option key={item.grade} value={item.grade}>{item.grade} — {item.score}</option>)}</Select></Field>
        <Field label="Grade point"><Input value={form.points} readOnly tabIndex={-1} placeholder="Selected automatically" /></Field>
        <AsyncSelect label="Year" loader={() => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS)} value={form.levelId} onChange={change('levelId')} />
        <AsyncSelect label="Academic session" loader={sessionLoader} value={form.sessionId} onChange={change('sessionId')} />
        <AsyncSelect label="Semester" loader={semesterLoader} value={form.semesterId} onChange={change('semesterId')} />
      </div>
      <div className="field-hint">Your selection will appear as <strong>{periodLabelFor(form.levelId, form.semesterId)}</strong>. Example: Year 1 — First Semester.</div>
      <Notice>Quality points = Credit Units × Grade Point. GPA for each semester is calculated from that semester's courses. CGPA is calculated from all your saved results across every year and semester.</Notice>
      <ActionError error={action.error} />
      <div className="modal-actions"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit" busy={action.busy} disabled={!contextualized || !form.grade || !form.credits} icon="check">{record ? 'Save changes' : 'Save result'}</Button></div>
    </form>
  </Modal>;
}

function CoursePlanner({ onChanged, onAddResult }) {
  const [courses, setCourses] = useState([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blankCourse); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function load() { try { const preferences = await authService.getPreferences(); setCourses(Array.isArray(preferences.plannedCourses) ? preferences.plannedCourses : []); } catch (e) { setError(e?.message || 'Unable to load your course list.'); } }
  useEffect(() => { load(); }, []);
  const change = key => e => setForm(prev => ({ ...prev, [key]: e.target.value }));
  function start(course = null) { setEditing(course); setForm(course ? { ...blankCourse, ...course } : { ...blankCourse }); setError(''); setOpen(true); }
  async function save(e) { e.preventDefault(); if (!form.code.trim() || !form.title.trim() || !form.credits || !form.sessionId || !form.semesterId || !form.levelId) return; setBusy(true); setError(''); try { const normalized = { ...form, code: form.code.trim().toUpperCase(), credits: Number(form.credits) }; const next = editing ? courses.map(c => c.id === editing.id ? { ...c, ...normalized } : c) : [...courses, { ...normalized, id: crypto.randomUUID() }]; await authService.updatePreferences({ plannedCourses: next }); setCourses(next); setOpen(false); onChanged?.(next); setForm({ ...blankCourse }); } catch (e) { setError(e?.message || 'Unable to save this course.'); } finally { setBusy(false); } }
  async function remove(id) { setBusy(true); setError(''); try { const next = courses.filter(c => c.id !== id); await authService.updatePreferences({ plannedCourses: next }); setCourses(next); onChanged?.(next); } catch (e) { setError(e?.message || 'Unable to remove this course.'); } finally { setBusy(false); } }
  const groups = new Map(); courses.forEach(course => { const key = `${course.levelId || ''}::${course.sessionId || ''}::${course.semesterId || ''}`; if (!groups.has(key)) groups.set(key, []); groups.get(key).push(course); });
  const orderedGroups = [...groups.entries()].sort(([, a], [, b]) => { const ay = FALLBACK_LEVELS.find(x => x.id === a[0]?.levelId)?.yearNumber || 99; const by = FALLBACK_LEVELS.find(x => x.id === b[0]?.levelId)?.yearNumber || 99; return ay - by || String(a[0]?.sessionId).localeCompare(String(b[0]?.sessionId)) || String(a[0]?.semesterId).localeCompare(String(b[0]?.semesterId)); });
  return <Panel title="My course planner" description="Organize courses by Year and semester. When a grade is released, use Add result so the grade becomes part of your GPA and CGPA." action={<Button icon="plus" onClick={() => start()}>Add course</Button>}>
    {error ? <p className="field-error" role="alert">{error}</p> : null}
    {courses.length ? <div className="semester-course-groups">{orderedGroups.map(([key, group]) => { const sample = group[0]; return <div className="semester-course-group" key={key}><div className="semester-course-heading"><div><strong>{periodLabelFor(sample.levelId, sample.semesterId)}</strong><span>{labelFor(FALLBACK_SESSIONS, sample.sessionId)}</span></div><Button variant="outline" onClick={() => start({ sessionId: sample.sessionId, semesterId: sample.semesterId, levelId: sample.levelId })}>Add course</Button></div><div className="table-scroll"><table><thead><tr><th>Course</th><th>Title</th><th>Credits</th><th>Actions</th></tr></thead><tbody>{group.map(course => <tr key={course.id}><td><strong>{course.code}</strong></td><td>{course.title}</td><td>{course.credits}</td><td><button type="button" className="text-button" onClick={() => onAddResult?.(course)}>Add result</button>{' '}<button type="button" className="text-button" onClick={() => start(course)}>Edit</button>{' '}<button type="button" className="text-button" onClick={() => remove(course.id)} disabled={busy}>Remove</button></td></tr>)}</tbody></table></div></div>; })}</div> : <div><Notice>No courses added yet. Add courses for Year 1, Year 2, Year 3 and so on, with First Semester and Second Semester under each year.</Notice><Button variant="outline" onClick={() => start()}>Add my first course</Button></div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit course' : 'Add semester course'} description="Choose the Year, academic session and semester where this course belongs."><form className="form-stack" onSubmit={save}><div className="form-grid"><Field label="Course code"><Input value={form.code} onChange={change('code')} placeholder="e.g. CSC 301" required /></Field><Field label="Course title"><Input value={form.title} onChange={change('title')} placeholder="e.g. Artificial Intelligence" required /></Field><Field label="Credit units"><Input value={form.credits} onChange={change('credits')} type="number" min="1" step="1" required /></Field><AsyncSelect label="Year" loader={() => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS)} value={form.levelId} onChange={change('levelId')} /><AsyncSelect label="Academic session" loader={() => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS)} value={form.sessionId} onChange={change('sessionId')} /><AsyncSelect label="Semester" loader={() => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS)} value={form.semesterId} onChange={change('semesterId')} /></div><div className="field-hint">This course belongs to <strong>{periodLabelFor(form.levelId, form.semesterId)}</strong>.</div><Notice>This planner entry does not affect your CGPA until you add the actual result and grade.</Notice><div className="modal-actions"><Button variant="outline" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" busy={busy} disabled={!form.sessionId || !form.semesterId || !form.levelId}>{editing ? 'Save course' : 'Add course'}</Button></div></form></Modal>
  </Panel>;
}

export function ResultDetails({ record, onClose }) { return <Modal open={!!record} onClose={onClose} title={record?.code || 'Result details'} description={record?.title} wide><div className="result-period-banner"><strong>{periodLabelFor(record?.levelId, record?.semesterId)}</strong><span>{record?.sessionName || labelFor(FALLBACK_SESSIONS, record?.sessionId)}</span></div><dl className="detail-grid">{resultColumns.filter(c => c.key !== 'title').map(c => <div key={c.key}><dt>{c.label}</dt><dd>{String(record?.[c.key] ?? '--')}</dd></div>)}</dl></Modal>; }

export default function Academic() {
  const [search, setSearch] = useState(''); const [filters, setFilters] = useState({ sessionId: '', semesterId: '', levelId: '' }); const resource = useResource(() => academicService.getResults(filters), [filters.sessionId, filters.semesterId, filters.levelId]); const summary = useResource(() => academicService.getSummary(filters), [filters.sessionId, filters.semesterId, filters.levelId]);
  const [editor, setEditor] = useState(new URLSearchParams(window.location.hash.split('?')[1]).get('add') === '1'); const [editing, setEditing] = useState(null); const [resultCourse, setResultCourse] = useState(null); const [viewing, setViewing] = useState(null); const [deleting, setDeleting] = useState(null); const [semester, setSemester] = useState(false); const change = key => e => setFilters({ ...filters, [key]: e.target.value }); function refresh() { resource.refresh(); summary.refresh(); }
  const sessionLoader = () => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS); const semesterLoader = () => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS); const levelLoader = () => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS);
  const filteredRows = (resource.data || []).filter(row => !search || `${row.code} ${row.title}`.toLowerCase().includes(search.toLowerCase()));
  const groupedResults = new Map(); filteredRows.forEach(row => { const key = `${row.levelId || ''}::${row.sessionId || ''}`; if (!groupedResults.has(key)) groupedResults.set(key, { levelId: row.levelId, sessionId: row.sessionId, semesters: new Map() }); const group = groupedResults.get(key); const semesterKey = row.semesterId || ''; if (!group.semesters.has(semesterKey)) group.semesters.set(semesterKey, []); group.semesters.get(semesterKey).push(row); });
  const orderedResultGroups = [...groupedResults.values()].sort((a, b) => (FALLBACK_LEVELS.find(x => x.id === a.levelId)?.yearNumber || 99) - (FALLBACK_LEVELS.find(x => x.id === b.levelId)?.yearNumber || 99) || String(a.sessionId).localeCompare(String(b.sessionId)));
  return <><PageHeader eyebrow="A HOME FOR EVERY RESULT" title="Your academic record." description="Add courses to individual semesters, record each released result, and let CGPA+ calculate your GPA and CGPA across your complete academic journey." actions={<Button icon="plus" onClick={() => { setEditing(null); setResultCourse(null); setEditor(true); }}>Add result</Button>} />
    <div className="record-summary"><div><span>Current CGPA</span><strong>{number(summary.data?.cgpa)}</strong></div><div><span>Selected GPA</span><strong>{number(summary.data?.gpa)}</strong></div><div><span>Total credits</span><strong>{number(summary.data?.totalCredits, 0)}</strong></div><div className="record-summary-links"><a href="#/app/calculator">Calculate GPA</a><a href="#/app/cgpa">Calculate CGPA</a></div></div>
    <CoursePlanner onAddResult={course => { setEditing(null); setResultCourse(course); setEditor(true); }} />
    <div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search course code or title..." /><Button variant="outline" icon="eye" onClick={() => setSemester(true)}>View semester</Button></div>
    <div className="table-filters"><AsyncSelect label="Academic session" loader={sessionLoader} value={filters.sessionId} onChange={change('sessionId')} /><AsyncSelect label="Semester" loader={semesterLoader} value={filters.semesterId} onChange={change('semesterId')} /><AsyncSelect label="Year" loader={levelLoader} value={filters.levelId} onChange={change('levelId')} /></div>
    <ConnectionState />
    {orderedResultGroups.length ? <div className="academic-result-years">{orderedResultGroups.map(group => <section className="academic-result-year" key={`${group.levelId}-${group.sessionId}`}><header><div><h2>{yearLabelFor(group.levelId)}</h2><span>{labelFor(FALLBACK_LEVELS, group.levelId)} · {labelFor(FALLBACK_SESSIONS, group.sessionId)}</span></div><Badge>{[...group.semesters.values()].reduce((sum, rows) => sum + rows.length, 0)} results</Badge></header>{[...group.semesters.entries()].sort(([a], [b]) => a === 'semester-first' ? -1 : b === 'semester-first' ? 1 : String(a).localeCompare(String(b))).map(([semesterId, rows]) => <div className="academic-result-semester" key={semesterId}><div className="academic-result-semester-heading"><div><strong>{periodLabelFor(group.levelId, semesterId)}</strong><span>{labelFor(FALLBACK_SESSIONS, group.sessionId)}</span></div><Badge>{rows.length} courses</Badge></div><DataTable columns={resultColumns} rows={rows} loading={resource.loading} onRowClick={row => setViewing(row)} emptyText="No results in this semester yet." /></div>)}</section>)}</div> : <Panel title="Your results" description="Your saved results will appear here under Year 1, Year 2, Year 3 and so on, with First Semester and Second Semester inside each year."><Notice>{resource.loading ? 'Loading your results...' : 'No results match the current filters. Add a result to begin your academic record.'}</Notice></Panel>}
    <ResultEditor open={editor} onClose={() => { setEditor(false); setResultCourse(null); }} record={editing} initialCourse={resultCourse} onSaved={refresh} />
    <ResultDetails record={viewing} onClose={() => setViewing(null)} />
    <ConfirmModal open={!!deleting} title="Delete result?" description="This removes the result from your academic record and CGPA calculation." onCancel={() => setDeleting(null)} onConfirm={() => { const row = deleting; setDeleting(null); academicService.deleteResult(row.id).then(refresh); }} />
    <Modal open={semester} onClose={() => setSemester(false)} title="Semester summary" description="GPA is calculated from the selected semester. CGPA always represents your complete saved academic record." wide><div className="record-summary"><div><span>Semester GPA</span><strong>{number(summary.data?.gpa)}</strong></div><div><span>Overall CGPA</span><strong>{number(summary.data?.cgpa)}</strong></div><div><span>Credits</span><strong>{number(summary.data?.totalCredits, 0)}</strong></div><div><span>Quality points</span><strong>{number(summary.data?.qualityPoints)}</strong></div></div></Modal>
  </>;
}
