import { useEffect, useMemo, useState } from 'react';
import { PageHeader, Button, Panel, Field, Input, Select, AsyncSelect, Notice, Badge } from '../../components/ui';
import { Modal, ConfirmModal, ActionError, useAction, ConnectionState } from '../../components/feedback';
import { useResource } from '../../hooks/useResource';
import { academicService } from '../../services/academic-service';
import { authService } from '../../services/auth-service';
import { number } from '../../utils/formatting';
import { GRADE_OPTIONS, FALLBACK_LEVELS, FALLBACK_SEMESTERS, FALLBACK_SESSIONS, academicPeriodLabel } from '../../data/uniport-catalogue';

const blank = { code: '', title: '', credits: '', grade: '', points: '', sessionId: '', semesterId: '', levelId: '', attemptType: 'regular', originalCourseCode: '' };
const blankCourse = { code: '', title: '', credits: '', sessionId: '', semesterId: '', levelId: '' };
const loadOrFallback = async (loader, fallback) => { try { const rows = await loader(); return Array.isArray(rows) && rows.length ? rows : fallback; } catch { return fallback; } };
const labelFor = (rows, id) => rows.find(row => row.id === id)?.name || id || '--';
const yearLabelFor = id => FALLBACK_LEVELS.find(row => row.id === id)?.yearName || labelFor(FALLBACK_LEVELS, id);
const periodLabelFor = (levelId, semesterId) => academicPeriodLabel(levelId, semesterId);
const levelNumber = id => FALLBACK_LEVELS.find(row => row.id === id)?.yearNumber || 99;
const semesterNumber = id => id === 'semester-first' ? 1 : id === 'semester-second' ? 2 : 99;

export const resultColumns = [
  { key: 'code', label: 'Course code' }, { key: 'title', label: 'Course title' }, { key: 'credits', label: 'Credit units' },
  { key: 'grade', label: 'Grade' }, { key: 'points', label: 'Grade points' }, { key: 'qualityPoints', label: 'Quality points' }, { key: 'attemptType', label: 'Attempt' },
];

export function ResultEditor({ open, onClose, record, onSaved, initialCourse }) {
  const [form, setForm] = useState(blank); const action = useAction();
  useEffect(() => { if (!open) return; let active = true; action.clear(); (async () => { let defaults = {}; try { const profile = await academicService.getProfile(); defaults = { sessionId: profile?.currentSessionId || '', semesterId: profile?.currentSemesterId || '', levelId: profile?.currentLevelId || '' }; } catch {} if (!active) return; setForm(record ? { ...blank, ...record, attemptType: record.attemptType || 'regular' } : { ...blank, ...defaults, ...(initialCourse || {}), sessionId: initialCourse?.sessionId || defaults.sessionId || FALLBACK_SESSIONS.at(-1)?.id, semesterId: initialCourse?.semesterId || defaults.semesterId || FALLBACK_SEMESTERS[0].id, levelId: initialCourse?.levelId || defaults.levelId || 'level-300' }); })(); return () => { active = false; }; }, [open, record, initialCourse]);
  const change = key => e => setForm(prev => ({ ...prev, [key]: e.target.value }));
  const gradeChange = e => { const grade = e.target.value; const option = GRADE_OPTIONS.find(item => item.grade === grade); setForm(prev => ({ ...prev, grade, points: option ? option.points : '' })); };
  const contextualized = form.sessionId && form.semesterId && form.levelId;
  return <Modal open={open} onClose={onClose} title={record ? 'Edit academic result' : 'Add an academic result'} description="Choose the Year and semester. Year 1 (100 Level) contains both First Semester and Second Semester, and the same structure continues for every year." wide>
    <form className="form-stack" onSubmit={e => { e.preventDefault(); if (!contextualized || !form.grade) return; const payload = { ...form, code: form.code.trim().toUpperCase(), credits: Number(form.credits), points: Number(form.points), attemptType: form.attemptType || 'regular', originalCourseCode: form.attemptType === 'carryover' ? (form.originalCourseCode || form.code).trim().toUpperCase() : '' }; action.run(() => record ? academicService.updateResult(record.id, payload) : academicService.saveResult(payload), () => { onSaved?.(); onClose(); }, record ? 'Your result was updated.' : 'Your result was saved.'); }}>
      <div className="form-grid"><Field label="Course code"><Input value={form.code} onChange={change('code')} placeholder="e.g. CSC 301" required maxLength={30} /></Field><Field label="Course title"><Input value={form.title} onChange={change('title')} placeholder="Full course title" required maxLength={180} /></Field><Field label="Credit units"><Input value={form.credits} onChange={change('credits')} type="number" required min="1" step="1" /></Field><Field label="Grade"><Select value={form.grade} onChange={gradeChange} required><option value="">Select your grade</option>{GRADE_OPTIONS.map(item => <option key={item.grade} value={item.grade}>{item.grade} — {item.score}</option>)}</Select></Field><Field label="Grade point"><Input value={form.points} readOnly tabIndex={-1} /></Field><AsyncSelect label="Year" loader={() => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS)} value={form.levelId} onChange={change('levelId')} /><AsyncSelect label="Academic session" loader={() => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS)} value={form.sessionId} onChange={change('sessionId')} /><AsyncSelect label="Semester" loader={() => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS)} value={form.semesterId} onChange={change('semesterId')} /></div>
      <Field label="Result type"><Select value={form.attemptType} onChange={change('attemptType')}><option value="regular">Regular result</option><option value="carryover">Carry-over / retake</option></Select></Field>
      {form.attemptType === 'carryover' && <Field label="Original course code" hint="Enter the failed course being retaken, for example CSC 301."><Input value={form.originalCourseCode || form.code} onChange={change('originalCourseCode')} placeholder="e.g. CSC 301" required /></Field>}
      <div className="field-hint">This result belongs to <strong>{periodLabelFor(form.levelId, form.semesterId)}</strong>. Carry-over keeps the old attempt in your history.</div><Notice>Quality points = Credit Units × Grade Point. Carry-over/retake results are stored separately so the original failed attempt is never lost.</Notice><ActionError error={action.error} /><div className="modal-actions"><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit" busy={action.busy} disabled={!contextualized || !form.grade || !form.credits} icon="check">{record ? 'Save changes' : 'Save result'}</Button></div>
    </form></Modal>;
}

function CoursePlanner({ onAddResult }) {
  const [courses, setCourses] = useState([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blankCourse); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function load() { try { const p = await authService.getPreferences(); setCourses(Array.isArray(p.plannedCourses) ? p.plannedCourses : []); } catch (e) { setError(e?.message || 'Unable to load your course list.'); } }
  useEffect(() => { load(); }, []);
  const change = key => e => setForm(prev => ({ ...prev, [key]: e.target.value }));
  function start(course = null, context = {}) { setEditing(course); setForm(course ? { ...blankCourse, ...course } : { ...blankCourse, ...context }); setError(''); setOpen(true); }
  async function save(e) { e.preventDefault(); if (!form.code.trim() || !form.title.trim() || !form.credits || !form.sessionId || !form.semesterId || !form.levelId) return; setBusy(true); setError(''); try { const normalized = { ...form, code: form.code.trim().toUpperCase(), credits: Number(form.credits) }; const next = editing ? courses.map(c => c.id === editing.id ? { ...c, ...normalized } : c) : [...courses, { ...normalized, id: crypto.randomUUID() }]; await authService.updatePreferences({ plannedCourses: next }); setCourses(next); setOpen(false); setForm(blankCourse); } catch (e) { setError(e?.message || 'Unable to save this course.'); } finally { setBusy(false); } }
  async function remove(id) { setBusy(true); try { const next = courses.filter(c => c.id !== id); await authService.updatePreferences({ plannedCourses: next }); setCourses(next); } catch (e) { setError(e?.message || 'Unable to remove this course.'); } finally { setBusy(false); } }
  const groups = new Map(); courses.forEach(course => { const key = `${course.levelId || ''}::${course.sessionId || ''}::${course.semesterId || ''}`; if (!groups.has(key)) groups.set(key, []); groups.get(key).push(course); });
  const ordered = [...groups.entries()].sort(([, a], [, b]) => levelNumber(a[0]?.levelId) - levelNumber(b[0]?.levelId) || semesterNumber(a[0]?.semesterId) - semesterNumber(b[0]?.semesterId));
  return <Panel title="My course planner" description="Courses you plan to take are separate from released results." action={<Button icon="plus" onClick={() => start()}>Add course</Button>}>
    {error && <p className="field-error">{error}</p>}{courses.length ? <div className="semester-course-groups">{ordered.map(([key, group]) => { const s = group[0]; return <div className="semester-course-group" key={key}><div className="semester-course-heading"><div><strong>{periodLabelFor(s.levelId, s.semesterId)}</strong><span>{labelFor(FALLBACK_SESSIONS, s.sessionId)}</span></div><Button variant="outline" onClick={() => start(null, { levelId: s.levelId, semesterId: s.semesterId, sessionId: s.sessionId })}>Add course</Button></div><div className="table-scroll"><table><thead><tr><th>Course</th><th>Title</th><th>Credits</th><th>Actions</th></tr></thead><tbody>{group.map(course => <tr key={course.id}><td><strong>{course.code}</strong></td><td>{course.title}</td><td>{course.credits}</td><td><button type="button" className="text-button" onClick={() => onAddResult?.(course)}>Add result</button>{' '}<button type="button" className="text-button" onClick={() => start(course)}>Edit</button>{' '}<button type="button" className="text-button" onClick={() => remove(course.id)} disabled={busy}>Remove</button></td></tr>)}</tbody></table></div></div>; })}</div> : <div><Notice>No planned courses yet.</Notice><Button variant="outline" onClick={() => start()}>Add my first course</Button></div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit course' : 'Add semester course'} description="Choose the Year, session and semester for this course."><form className="form-stack" onSubmit={save}><div className="form-grid"><Field label="Course code"><Input value={form.code} onChange={change('code')} required /></Field><Field label="Course title"><Input value={form.title} onChange={change('title')} required /></Field><Field label="Credit units"><Input value={form.credits} onChange={change('credits')} type="number" min="1" step="1" required /></Field><AsyncSelect label="Year" loader={() => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS)} value={form.levelId} onChange={change('levelId')} /><AsyncSelect label="Academic session" loader={() => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS)} value={form.sessionId} onChange={change('sessionId')} /><AsyncSelect label="Semester" loader={() => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS)} value={form.semesterId} onChange={change('semesterId')} /></div><Notice>This planner course does not affect CGPA until you record its actual result.</Notice><div className="modal-actions"><Button variant="outline" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" busy={busy} disabled={!form.sessionId || !form.semesterId || !form.levelId}>{editing ? 'Save course' : 'Add course'}</Button></div></form></Modal>
  </Panel>;
}

export function ResultDetails({ record, onClose }) { return <Modal open={!!record} onClose={onClose} title={record?.code || 'Result details'} description={record?.title} wide><div className="result-period-banner"><strong>{periodLabelFor(record?.levelId, record?.semesterId)}</strong><span>{record?.sessionName || labelFor(FALLBACK_SESSIONS, record?.sessionId)}</span></div><Notice>Grade point is the numeric value assigned to your letter grade. Quality points are Credit Units × Grade Point, and they are used to calculate GPA/CGPA.</Notice><dl className="detail-grid">{resultColumns.map(c => <div key={c.key}><dt>{c.label}</dt><dd>{c.key === 'attemptType' ? (record?.attemptType === 'carryover' ? 'Carry-over / retake' : 'Regular') : String(record?.[c.key] ?? '--')}</dd></div>)}</dl></Modal>; }

export default function Academic() {
  const [search, setSearch] = useState(''); const [filters, setFilters] = useState({ sessionId: '', semesterId: '', levelId: '' }); const resource = useResource(() => academicService.getResults(filters), [filters.sessionId, filters.semesterId, filters.levelId]); const summary = useResource(() => academicService.getSummary(filters), [filters.sessionId, filters.semesterId, filters.levelId]);
  const [editor, setEditor] = useState(new URLSearchParams(window.location.hash.split('?')[1]).get('add') === '1'); const [editing, setEditing] = useState(null); const [resultCourse, setResultCourse] = useState(null); const [viewing, setViewing] = useState(null); const [deleting, setDeleting] = useState(null); const [bulkAction, setBulkAction] = useState(null); const [semester, setSemester] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const change = key => e => setFilters(prev => ({ ...prev, [key]: e.target.value })); const refresh = () => { resource.refresh(); summary.refresh(); };
  const sessionLoader = () => loadOrFallback(() => academicService.getAcademicSessions(), FALLBACK_SESSIONS); const semesterLoader = () => loadOrFallback(() => academicService.getSemesters(), FALLBACK_SEMESTERS); const levelLoader = () => loadOrFallback(() => academicService.getLevels(), FALLBACK_LEVELS);
  const filteredRows = useMemo(() => (resource.data || []).filter(row => !search || `${row.code} ${row.title}`.toLowerCase().includes(search.toLowerCase())), [resource.data, search]);
  const groupedResults = useMemo(() => { const groups = new Map(); filteredRows.forEach(row => { const key = row.levelId || 'unknown'; if (!groups.has(key)) groups.set(key, { levelId: row.levelId, semesters: new Map() }); const group = groups.get(key); const semesterId = row.semesterId || ''; if (!group.semesters.has(semesterId)) group.semesters.set(semesterId, []); group.semesters.get(semesterId).push(row); }); return [...groups.values()].sort((a, b) => levelNumber(a.levelId) - levelNumber(b.levelId)); }, [filteredRows]);
  const currentBulkRows = bulkAction?.type === 'year' ? filteredRows.filter(r => r.levelId === bulkAction.levelId) : bulkAction?.type === 'semester' ? filteredRows.filter(r => r.levelId === bulkAction.levelId && r.semesterId === bulkAction.semesterId) : [];
  const deleteRows = async rows => { setBusy(true); setError(''); try { for (const row of rows) await academicService.deleteResult(row.id); refresh(); } catch (e) { setError(e?.message || 'Unable to delete these records.'); } finally { setBusy(false); setBulkAction(null); } };
  const moveRows = async (rows, field, value) => { setBusy(true); setError(''); try { for (const row of rows) await academicService.updateResult(row.id, { code: row.code, title: row.title, credits: row.credits, grade: row.grade, points: row.points, sessionId: row.sessionId, semesterId: field === 'semesterId' ? value : row.semesterId, levelId: field === 'levelId' ? value : row.levelId, attemptType: row.attemptType || 'regular', originalCourseCode: row.originalCourseCode || '' }); refresh(); } catch (e) { setError(e?.message || 'Unable to move these records.'); } finally { setBusy(false); setBulkAction(null); } };
  return <><PageHeader eyebrow="A HOME FOR EVERY RESULT" title="Your academic record." description="Each year is a container: Year 1 (100 Level) contains First Semester and Second Semester, Year 2 (200 Level) contains First Semester and Second Semester, and so on." actions={<Button icon="plus" onClick={() => { setEditing(null); setResultCourse(null); setEditor(true); }}>Add result</Button>} />
    <div className="record-summary"><div><span>Current CGPA</span><strong>{number(summary.data?.cgpa)}</strong></div><div><span>Selected GPA</span><strong>{number(summary.data?.gpa)}</strong></div><div><span>Total credits</span><strong>{number(summary.data?.totalCredits, 0)}</strong></div><div className="record-summary-links"><a href="#/app/calculator">Calculate GPA</a><a href="#/app/cgpa">Calculate CGPA</a></div></div>
    <CoursePlanner onAddResult={course => { setEditing(null); setResultCourse(course); setEditor(true); }} />
    <div className="table-toolbar"><input className="input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search course code or title..." aria-label="Search course code or title" /><Button variant="outline" icon="eye" onClick={() => setSemester(true)}>View semester</Button></div>
    <div className="table-filters"><AsyncSelect label="Academic session" loader={sessionLoader} value={filters.sessionId} onChange={change('sessionId')} /><AsyncSelect label="Semester" loader={semesterLoader} value={filters.semesterId} onChange={change('semesterId')} /><AsyncSelect label="Year" loader={levelLoader} value={filters.levelId} onChange={change('levelId')} /></div>
    {error && <Notice tone="danger" icon="alert">{error}</Notice>}{resource.status === 'loading' && <ConnectionState resource={resource} title="academic results" />}
    {groupedResults.length ? <div className="academic-result-years">{groupedResults.map(group => <section className="academic-result-year" key={group.levelId}><header><div><h2>{yearLabelFor(group.levelId)} <span>({labelFor(FALLBACK_LEVELS, group.levelId)})</span></h2><span>First and Second Semester stay together inside this year.</span></div><div className="row-actions"><Badge>{[...group.semesters.values()].reduce((sum, rows) => sum + rows.length, 0)} results</Badge><button type="button" className="text-button" onClick={() => setBulkAction({ type: 'year', levelId: group.levelId, mode: 'edit' })}>Edit year</button><button type="button" className="text-button danger" onClick={() => setBulkAction({ type: 'year', levelId: group.levelId, mode: 'delete' })}>Delete year</button></div></header>{[...group.semesters.entries()].sort(([a], [b]) => semesterNumber(a) - semesterNumber(b)).map(([semesterId, rows]) => <div className="academic-result-semester" key={semesterId}><div className="academic-result-semester-heading"><div><strong>{periodLabelFor(group.levelId, semesterId)}</strong><span>{labelFor(FALLBACK_SESSIONS, rows[0]?.sessionId)} · {rows.length} courses</span></div><div className="row-actions"><button type="button" className="text-button" onClick={() => setBulkAction({ type: 'semester', levelId: group.levelId, semesterId, mode: 'edit' })}>Edit semester</button><button type="button" className="text-button danger" onClick={() => setBulkAction({ type: 'semester', levelId: group.levelId, semesterId, mode: 'delete' })}>Delete semester</button></div></div><div className="table-scroll"><table><thead><tr><th>Course</th><th>Title</th><th>Credits</th><th>Grade</th><th>Grade point</th><th>Quality points</th><th>Attempt</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.code}</strong></td><td>{row.title}</td><td>{row.credits}</td><td><Badge tone={Number(row.points) === 0 ? 'danger' : 'success'}>{row.grade}</Badge></td><td>{number(row.points)}</td><td>{number(row.qualityPoints)}</td><td>{row.attemptType === 'carryover' ? <Badge tone="warning">Carry-over</Badge> : 'Regular'}</td><td><button type="button" className="text-button" onClick={() => { setEditing(row); setResultCourse(null); setEditor(true); }}>Edit</button>{' '}<button type="button" className="text-button" onClick={() => setViewing(row)}>View</button>{' '}<button type="button" className="text-button danger" onClick={() => setDeleting(row)}>Delete</button></td></tr>)}</tbody></table></div></div>)}</section>)}</div> : resource.status !== 'loading' ? <Panel title="Your results" description="Your saved results will appear under the correct Year and its two semesters."><Notice>No results match the current filters. Add a result to begin your academic record.</Notice></Panel> : null}
    <ResultEditor open={editor} onClose={() => { setEditor(false); setResultCourse(null); }} record={editing} initialCourse={resultCourse} onSaved={refresh} />
    <ResultDetails record={viewing} onClose={() => setViewing(null)} />
    <ConfirmModal open={!!deleting} title="Delete result?" description="This removes the result from your academic record and CGPA calculation." actionLabel="Delete result" dangerous onClose={() => setDeleting(null)} onConfirm={async () => { const row = deleting; await academicService.deleteResult(row.id); refresh(); setDeleting(null); }} />
    <ConfirmModal open={!!bulkAction && bulkAction.mode === 'delete'} title={`Delete ${bulkAction?.type === 'year' ? 'year' : 'semester'}?`} description={`This will permanently remove all ${currentBulkRows.length} result(s) in this ${bulkAction?.type === 'year' ? 'year' : 'semester'}. This cannot be undone.`} actionLabel="Delete records" dangerous onClose={() => setBulkAction(null)} onConfirm={() => deleteRows(currentBulkRows)} />
    <Modal open={!!bulkAction && bulkAction.mode === 'edit'} onClose={() => setBulkAction(null)} title={`Edit ${bulkAction?.type === 'year' ? 'year' : 'semester'}`} description="Move every result in this group to another academic category."><div className="form-stack"><Notice>{currentBulkRows.length} result(s) will be moved together.</Notice><Field label={bulkAction?.type === 'year' ? 'Move all results to year' : 'Move all results to semester'}><Select defaultValue="" onChange={e => e.target.value && moveRows(currentBulkRows, bulkAction.type === 'year' ? 'levelId' : 'semesterId', e.target.value)} disabled={busy}><option value="">Select destination</option>{(bulkAction?.type === 'year' ? FALLBACK_LEVELS : FALLBACK_SEMESTERS).map(row => <option key={row.id} value={row.id}>{row.yearName || row.name}</option>)}</Select></Field><Button variant="outline" onClick={() => setBulkAction(null)}>Cancel</Button></div></Modal>
    <Modal open={semester} onClose={() => setSemester(false)} title="Semester summary" description="GPA is calculated from the selected semester. CGPA represents your complete saved academic record." wide><div className="record-summary"><div><span>Semester GPA</span><strong>{number(summary.data?.gpa)}</strong></div><div><span>Overall CGPA</span><strong>{number(summary.data?.cgpa)}</strong></div><div><span>Credits</span><strong>{number(summary.data?.totalCredits, 0)}</strong></div><div><span>Quality points</span><strong>{number(summary.data?.qualityPoints)}</strong></div></div></Modal>
  </>;
}
