import { PageHeader, Button, Stat, Panel, AsyncSelect } from '../../components/ui';
import { ConnectionState } from '../../components/feedback';
import { LineChart, BarChart, DonutChart } from '../../components/charts';
import { academicService } from '../../services/academic-service';
import { useResource } from '../../hooks/useResource';
import { number } from '../../utils/formatting';
import { useState } from 'react';

export default function Analytics() {
  const [session, setSession] = useState('');
  const resource = useResource(() => academicService.getAnalytics({ sessionId: session }), [session]);
  const stats = resource.data?.stats || {};
  const chart = (title, render) => <Panel title={title}><ConnectionState resource={resource} title={title.toLowerCase()} emptyTitle="Your progress will take shape here." emptyDescription="Add academic records through the connected service to unlock this chart." compact={false}>{render}</ConnectionState></Panel>;
  return <><PageHeader eyebrow="SEE THE PATTERNS. FIND YOUR DIRECTION." title="A little perspective on your progress." description="Understand your performance across courses, credits and semesters." actions={<Button href="#/app/reports" icon="file" variant="outline">Academic report</Button>} /><div className="analytics-filter"><AsyncSelect label="Academic session" loader={() => academicService.getAcademicSessions()} value={session} onChange={e => setSession(e.target.value)} placeholder="All sessions" required={false} /></div><div className="stats-grid"><Stat label="Current CGPA" value={number(stats.cgpa)} accent /><Stat label="Highest GPA" value={number(stats.highestGpa)} icon="chart" /><Stat label="Lowest GPA" value={number(stats.lowestGpa)} icon="bars" /><Stat label="Average GPA" value={number(stats.averageGpa)} icon="calculator" /></div><div className="analytics-secondary"><div><span>Total credits</span><strong>{number(stats.totalCredits, 0)}</strong></div><div><span>Failed courses</span><strong>{stats.failedCourses ?? '--'}</strong></div><div><span>Repeated courses</span><strong>{stats.repeatedCourses ?? '--'}</strong></div><div><span>Best semester</span><strong>{stats.bestSemester || '--'}</strong></div><div><span>Weakest semester</span><strong>{stats.weakestSemester || '--'}</strong></div></div><div className="two-panel-grid">{chart('GPA by semester', d => <LineChart values={(d.series || []).map(s => s.gpa)} labels={(d.series || []).map(s => s.label)} max={d.maxPoint || 5} />)}{chart('CGPA progression', d => <LineChart values={(d.series || []).map(s => s.cgpa)} labels={(d.series || []).map(s => s.label)} max={d.maxPoint || 5} color="var(--chart-blue)" />)}{chart('Credit units completed', d => <BarChart values={(d.series || []).map(s => s.credits)} labels={(d.series || []).map(s => s.label)} />)}{chart('Grade distribution', d => <DonutChart items={d.grades || []} />)}{chart('Passed vs failed courses', d => <BarChart values={[d.passed || 0, d.failed || 0]} labels={['Passed', 'Failed']} />)}<Panel title="From perspective to a plan" description="Make your next step an informed one."><div className="analytics-next"><p>Use what you learn to explore a target or plan for your remaining semesters.</p><Button href="#/app/target" endIcon="arrow">Set a target CGPA</Button><Button href="#/app/projection" variant="outline" endIcon="arrow">Explore scenarios</Button></div></Panel></div></>;
}