import { useState } from 'react';
import { PageHeader, Button, Panel, Stat, Badge, Notice, Tabs } from '../../components/ui';
import { ConnectionState, EmptyState } from '../../components/feedback';
import { Icon } from '../../components/Icon';
import { Progress } from '../../components/charts';
import { DataTable, SearchBox } from '../../components/table';
import { academicService } from '../../services/academic-service';
import { useResource } from '../../hooks/useResource';
import { number, titleCase } from '../../utils/formatting';

export function Timeline() {
  const resource = useResource(() => academicService.getAcademicTimeline());
  return <><PageHeader eyebrow="CHAPTER BY CHAPTER" title="Your academic journey." description="A connected view of your levels, semesters and milestones. Every step belongs to your story." actions={<Button variant="outline" href="#/app/academic" icon="book">Academic record</Button>} /><Panel title="From first steps to your final year" description="Levels and completion states come from your actual programme data."><ConnectionState resource={resource} title="academic timeline" emptyTitle="Your journey has not been mapped yet." emptyDescription="Your programme's levels and recorded semesters will create your timeline.">{data => data.levels?.length ? <div className="academic-timeline">{data.levels.map(level => <section className={`timeline-level status-${level.status}`} key={level.id}><div className="timeline-marker"><Icon name={level.status === 'completed' ? 'check' : level.status === 'current' ? 'arrow' : 'timeline'} size={18} /></div><div><header><h3>{level.name}</h3><Badge tone={level.status === 'completed' ? 'success' : level.status === 'current' ? 'info' : 'neutral'}>{titleCase(level.status)}</Badge></header><div className="timeline-semesters">{(level.semesters || []).map(sem => <div key={sem.id}><Icon name={sem.status === 'completed' ? 'check' : sem.status === 'current' ? 'arrow' : 'book'} size={16} /><span>{sem.name}<small>{sem.sessionName || 'Session not assigned'}</small></span><Badge>{titleCase(sem.status)}</Badge></div>)}</div></div></section>)}</div> : <EmptyState title="No academic timeline available." description="Academic levels will be supplied by the backend." />}</ConnectionState></Panel><Notice>No levels or completed semesters are inferred. Timeline progress is supplied by the academic service.</Notice></>;
}

export function Graduation() {
  const resource = useResource(() => academicService.getGraduationProgress());
  const data = resource.data || {};
  return <><PageHeader eyebrow="KEEP THE BIG PICTURE IN VIEW" title="Your graduation plan." description="Credit progress, milestones and courses that need attention. A plan for your next chapter." actions={<Button href="#/app/failed" icon="alert" variant="outline">Course attention</Button>} />{resource.error && <ConnectionState resource={resource} title="graduation progress" compact />}<div className="stats-grid"><Stat label="Graduation planning progress" value={data.percent == null ? '--' : `${number(data.percent, 0)}%`} icon="graduation" accent /><Stat label="Completed credit units" value={number(data.completedCredits, 0)} icon="check" /><Stat label="Remaining credit units" value={number(data.remainingCredits, 0)} icon="book" /><Stat label="Current CGPA" value={number(data.cgpa)} icon="chart" /></div><div className="two-panel-grid"><Panel title="One step closer" description="Your programme determines the credit requirement."><Progress value={data.percent ?? null} label="Credit progress" detail={data.requiredCredits ? `${data.completedCredits} / ${data.requiredCredits} units` : 'Programme requirement pending'} /><dl className="semester-details"><div><dt>Current level</dt><dd>{data.currentLevel || '--'}</dd></div><div><dt>Outstanding courses</dt><dd>{data.outstandingCount ?? '--'}</dd></div><div><dt>Failed courses</dt><dd>{data.failedCount ?? '--'}</dd></div><div><dt>Official eligibility</dt><dd>Determined by UniPort</dd></div></dl></Panel><Panel title="Academic milestones"><ConnectionState resource={resource} title="milestones" emptyTitle="Your milestones will appear here.">{d => d.milestones?.length ? <ul className="milestone-list">{d.milestones.map(m => <li key={m.id}><Icon name={m.completed ? 'check' : 'target'} size={18} /><span>{m.title}</span><Badge tone={m.completed ? 'success' : 'neutral'}>{m.completed ? 'Completed' : 'Outstanding'}</Badge></li>)}</ul> : <EmptyState compact title="Milestones need your programme data." description="No graduation requirements are invented." />}</ConnectionState></Panel></div><Notice tone="warning" icon="graduation">CGPA+ is an academic planning tool and does not replace official University of Port Harcourt clearance or transcripts. Graduation eligibility is never determined by this frontend.</Notice></>;
}

export function CourseAttention() {
  const [tab, setTab] = useState('failed');
  const [search, setSearch] = useState('');
  const loaders = { failed: academicService.getFailedCourses, repeated: academicService.getRepeatedCourses, outstanding: academicService.getOutstandingCourses, attention: academicService.getAttentionCourses };
  const resource = useResource(() => loaders[tab](), [tab]);
  const columns = [{ key: 'code', label: 'Course code' }, { key: 'title', label: 'Course title' }, { key: 'sessionName', label: 'Session' }, { key: 'semesterName', label: 'Semester' }, { key: 'credits', label: 'Units' }, { key: 'grade', label: 'Grade' }, { key: 'status', label: 'Status', render: v => <Badge tone={v === 'failed' ? 'danger' : 'warning'}>{titleCase(v) || 'Needs review'}</Badge> }, { key: 'note', label: 'Academic note' }];
  return <><PageHeader eyebrow="NOTICE IT. PLAN FOR IT." title="A little attention goes a long way." description="Keep failed, repeated and outstanding courses visible without guessing academic rules." /><Tabs value={tab} onChange={setTab} options={[{ value: 'failed', label: 'Failed courses' }, { value: 'repeated', label: 'Repeated courses' }, { value: 'outstanding', label: 'Outstanding courses' }, { value: 'attention', label: 'Requires attention' }]} /><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Find a course..." /><Button variant="outline" icon="refresh" onClick={resource.refresh}>Refresh</Button></div><DataTable columns={columns} resource={resource} search={search} emptyTitle={`No ${tab === 'attention' ? 'flagged' : tab} courses found.`} emptyDescription="This list is supplied by the academic service, not inferred from an unverified grading rule." /><Notice icon="shield">Repeat-course treatment and outstanding requirements depend on the official academic policy supplied by the backend. This page does not invent or apply those rules.</Notice></>;
}