import { PublicCta, PublicHeading } from './Pages';

export function CookiePolicy() {
  return <><PublicHeading eyebrow="COOKIES & TRACKING" title="Cookie policy" description="How CGPA+ UniPort handles browser storage, consent and optional analytics." meta={[['lock', 'No advertising cookies'], ['shield', 'Consent controlled'], ['eye', 'Transparent tracking']]} /><main className="container public-content legal-prose"><section><h2>What we use</h2><p>CGPA+ UniPort may use essential browser storage for preferences such as your selected appearance and, where enabled, your cookie-consent choice. Public calculators can work without an account.</p></section><section><h2>Optional analytics</h2><p>Analytics are optional. If analytics is configured for this deployment, the analytics script is loaded only after you give analytics consent. No analytics identifier is bundled into the application code.</p></section><section><h2>No advertising cookies</h2><p>This release does not intentionally use advertising cookies, behavioural advertising pixels or third-party advertising trackers.</p></section><section><h2>Changing your choice</h2><p>You can clear the site's stored consent and preference data through your browser settings. If a consent-management control is provided in the interface, use it to change your choice.</p></section><section><h2>Third-party resources</h2><p>The site may load external resources such as web fonts. Those providers can receive normal network information when a browser requests their resources. Production deployments should self-host resources where practical and review every third-party service before launch.</p></section><section><h2>Policy review</h2><p>This policy should be reviewed against the services actually enabled on the production deployment and applicable Nigerian data-protection requirements before launch.</p></section></main><PublicCta eyebrow="PRIVACY BY DESIGN" title="See the full privacy policy." copy="Understand what information CGPA+ may handle and what remains in your browser." primary={['Privacy policy','/privacy']} /></>;
}

export function ThankYou() {
  return <><PublicHeading eyebrow="MESSAGE RECEIVED" title="Thanks for reaching out." description="Your next step is simple: keep your reference details if the form gave you one, and return to your CGPA+ journey when you're ready." meta={[['check', 'Request flow complete'], ['message', 'Support centre']]}/><div className="container public-content"><div className="empty-state"><span className="empty-icon">✓</span><h2>You're all set.</h2><p>CGPA+ will only describe a request as submitted when the connected service confirms it.</p><ButtonLink href="/">Return home</ButtonLink></div></div></>;
}
function ButtonLink({ href, children }) { return <a className="button button-primary" href={`#${href}`}>{children}</a>; }
