import { PageHeader, Stat, Panel, Button, Badge } from '../../components/ui';
import { ConnectionState } from '../../components/feedback';
import { LineChart, BarChart } from '../../components/charts';
import { Icon } from '../../components/Icon';
import { adminService } from '../../services/admin-service';
import { useResource } from '../../hooks/useResource';
import { dateTime, number } from '../../utils/formatting';

export default function AdminDashboard() {
  const resource = useResource(() => adminService.getDashboard());
  const stats = resource.data?.stats || {};
  const labels = [['totalStudents', 'Total students', 'users'], ['activeStudents', 'Active students', 'user'], ['newStudents', 'New students', 'plus'], ['verifiedAccounts', 'Verified accounts', 'shield'], ['supportRequests', 'Support requests', 'message']];
  const series = (data, name) => data.charts?.[name] || [];
  const chart = (title, render) => <Panel title={title}><ConnectionState resource={resource} title={title.toLowerCase()} emptyTitle="No platform analytics yet.">{render}</ConnectionState></Panel>;
  return <><PageHeader eyebrow="CGPA+ UNIPORT ADMINISTRATION" title="A clear view of the platform." description="Students, academic data, notifications and support. The operational picture, in one place." actions={<Button variant="outline" icon="refresh" onClick={resource.refresh}>Refresh overview</Button>} /><div className="stats-grid stats-three">{labels.map(([key, label, icon], i) => <Stat key={key} label={label} value={number(stats[key], 0)} icon={icon} accent={i === 0} hint="Provided by the authorized admin service" />)}</div><div className="two-panel-grid">{chart('User growth', d => <LineChart values={series(d, 'userGrowth').map(r => r.value)} labels={series(d, 'userGrowth').map(r => r.label)} max={Math.max(1, ...series(d, 'userGrowth').map(r => r.value))} />)}{chart('Registration trends', d => <BarChart values={series(d, 'registrations').map(r => r.value)} labels={series(d, 'registrations').map(r => r.label)} />)}{chart('Active users', d => <LineChart values={series(d, 'activeUsers').map(r => r.value)} labels={series(d, 'activeUsers').map(r => r.label)} max={Math.max(1, ...series(d, 'activeUsers').map(r => r.value))} color="var(--chart-blue)" />)}</div><div className="admin-recent-grid">{[['recentStudents', 'Recent students', '/admin/students', 'user'], ['recentTickets', 'Recent support requests', '/admin/support', 'message'], ['activity', 'Recent system activity', '/admin/logs', 'shield']].map(([key, title, href, icon]) => <Panel title={title} key={key} action={<a className="small-link" href={`#${href}`}><Icon name="arrow" size={14} /></a>}><ConnectionState resource={{ ...resource, data: resource.data?.[key] }} title={title.toLowerCase()} emptyTitle="Nothing to show yet." emptyDescription="Activity will appear when supplied by the backend.">{rows => <div className="admin-activity-list">{rows.slice(0, 5).map(row => <a href={`#${href}`} key={row.id}><Icon name={icon} size={18} /><span><strong>{row.fullName || row.subject || row.action}</strong><small>{row.email || dateTime(row.createdAt)}</small></span>{row.status && <Badge>{row.status}</Badge>}</a>)}</div>}</ConnectionState></Panel>)}</div><div className="admin-quick-links"><a href="#/admin/students"><Icon name="users" size={19} /><span>View student directory</span><Icon name="arrow" size={16} /></a><a href="#/admin/academic"><Icon name="book" size={19} /><span>Manage academic data</span><Icon name="arrow" size={16} /></a><a href="#/admin/notifications"><Icon name="bell" size={19} /><span>Compose an announcement</span><Icon name="arrow" size={16} /></a></div></>;
}